language: python
sudo: false
python:
- '2.7'
- '3.3'
install:
  - pip install pytest pytest-cov coverage coveralls
  - pip install -r requirements.txt
script:   # Add pytest-pep8 when ready, leaving out for the moment
  - PYTHONPATH=. py.test --cov=api --cov-report=term-missing test/unit_tests/
after_success:
  - coveralls
