sudo: required
dist: trusty

services:
  - mongodb
env:
  global:
    secure: HELJx6WPr+W2S0FV47KkRdlS9NCqlMcdRMK8xWgRqqrEPv24KEvNnHxCy0tRbzITqadYtyvI1MtqtmpG04uty8Gpkc7w6L6LMJ/OuLG0gVX7AnaUovYTlY04m1/L9oyzOrTDXk5J/BKbcyiz7uJtkTc/A8MMZAFfZh7hmhLID78=

install:
  - bin/install-ubuntu.sh
  - test/bin/setup-integration-tests-ubuntu.sh

script:
  - SCITRAN_PERSISTENT_DB_PORT=27017 test/bin/run-tests-ubuntu.sh

after_success:
  - coveralls
  # docker/build-trigger.sh contains the rules for when to, and not to trigger
  - if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
      ./docker/build-trigger.sh Tag "${TRAVIS_TAG}" "${BUILD_TRIGGER_URL}" ;
      ./docker/build-trigger.sh Branch "${TRAVIS_BRANCH}" "${BUILD_TRIGGER_URL}" ;
    fi
