language: python
python:
- '2.7'
- '3.3'
- pypy
addons:
  apt:
    sources:
      - pypy
    packages:
      - pypy
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage -vv -exe test/unit_tests
