dist: trusty
sudo: required

services:
- docker

env:
  global:
  - DOCKER_DIR="$HOME/.cache/docker"

cache:
  directories:
  - $DOCKER_DIR

before_install:
- sudo apt-get update
- sudo apt-get -y install docker-ce realpath
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS

install: true

script:
- test -f "$DOCKER_DIR/image.tar" && docker load -i "$DOCKER_DIR/image.tar" || true
- docker build -t core:base --target base .
- docker build -t core:dist --target dist --build-arg VCS_BRANCH="$TRAVIS_BRANCH" --build-arg VCS_COMMIT="$TRAVIS_COMMIT" .
- docker build -t core:testing --target testing .
- docker save -o "$DOCKER_DIR/image.tar" $(docker history -q core:base | grep -v '<missing>') $(docker history -q core:dist | grep -v '<missing>')
- ./tests/bin/docker-tests.sh --image core:testing

after_success:
# Code coverage report for all master commits and all pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
      bash <(curl -s https://codecov.io/bash) -cF python;
  fi

# Build swagger docs and push them to gh-pages
- if [ "$TRAVIS_EVENT_TYPE" == "push" ] || [ -n "$TRAVIS_TAG" ]; then
      git config --global user.email "travis@travis-ci.org";
      git config --global user.name "Travis CI";
      git config --global push.default simple;

      if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
          ./bin/push-docs.sh "$GIT_REMOTE" branches "$TRAVIS_BRANCH" "Travis Core Docs Build - $TRAVIS_BUILD_NUMBER";
      else
          ./bin/push-docs.sh "$GIT_REMOTE" tags "$TRAVIS_TAG" "Travis Core Docs Build - $TRAVIS_BUILD_NUMBER";
      fi
  fi

# Tag and push flywheel/core image (master >> :latest, tag >> :tag)
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
      docker tag core:dist flywheel/core:latest;
      docker push flywheel/core:latest;
  fi
- if [ -n "$TRAVIS_TAG" ]; then
      docker tag core:dist flywheel/core:$TRAVIS_TAG;
      docker push flywheel/core:$TRAVIS_TAG;
  fi

# Temporary: tag and push unit-improvements-backport-1-rebased, too
# TODO (Ambrus) Remove before merge
- if [ "$TRAVIS_BRANCH" == "unit-improvements-backport-1-rebased" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
      docker tag core:dist flywheel/core:refactor;
      docker push flywheel/core:refactor;
  fi
